export const teamName = {
  "Germany": "Allemagne",
  "Spain": "Espagne",
  "Paris Saint Germain": "Paris St Germain",
  "Barcelona" : "FC Barcelone",
  "England" : "Angleterre",
  "Wales" : "Pays de Galles",
  "Netherlands" : "Pays Bas",
  "Belgium" : "Belgique",
  "Switzerland" : "Suisse",
  "Scotland" : "Ecosse",
  "Italy" : "Italie",
  "Sweden" : "Suede",
  "Austria" : "Autriche",
  "Belarus" : "Bielorussie",
  "Morocco" : "Maroc",
      "Ivory Coast" : "Cote d'Ivoire",
      "Algeria" : "Algerie",
  "Moldova" : "Moldavie",
  "Cyprus" : "Chypre",
  "Norway" : "Norvege",
  "Hungary" : "Hongrie",
  "Central African Republic" : "Centrafrique",
  "Cape Verde Islands" : "Cap Vert",
    "Belarus" : "Bielorussie",
    "Croatia" : "Croatie",
    "Denmark" : "Danemark",
    "Malta" : "Malte",
    "Lithuania" : "Lituanie",
     "New York Red Bulls" : "New York RB",
  "Philadelphia Union" : "Philadelphia",
};